### PR TITLE
Fixed an exception caused by issues with calculated buffer sizes. 

### PR DESCRIPTION
**Pull request by onimitch**
Switched back to relying on zero termination.
Also added a check to return early if the string is empty.

The important bit was the `source_length + 1` line 33. Without the `+1` ffi.copy was going past the allocated memory for cbuffer and it then caused an access violation exception. It was a bit hard to track down as the exception wasn't very predictable, but I've now run with this code all day and I'm reasonably confident (I'm aware I did say this last time!) that this is stable. It's certainly safer code than my previous changes.

### CODE REVIEW

**Comment by ThornyFFXI** [comment]
I am not entirely sure this calculated buffer method is the best way to do things.  Using string.len in lua will return the amount of bytes the string takes, but a shift-jis string is 1-2 bytes per character, while some pages of utf-8 are up to 4 bytes per character.  This means that some conversions will take considerably more space in UTF-8 than they will in shift-jis, and the reverse is also possible.

I think a more prudent approach is to allocate a larger memory set; if my initial code with the fixed memory size is insufficient then perhaps a stepwise function or a multiplier of 4.  This memory is going to be freed again anyway almost immediately, there shouldn't be that much concern about allocating too much.. but as you've seen there are consequences to allocating too little.  It's possible that the current limits are sufficient for any string in FFXI, but we don't know that unless it's been unit tested with all resources, and ideally the functions should support any shift-jis not just that which comes from FFXI resources.

**Comment by ThornyFFXI** [comment]
It seems your code aims to use a secondary conversion call to get the size, but the official documentation on these functions says:

```f successful, returns the number of bytes written to the buffer pointed to by lpMultiByteStr. If the function succeeds and cbMultiByte is 0, the return value is the required size, in bytes, for the buffer indicated by lpMultiByteStr. Also see dwFlags for info about how the WC_ERR_INVALID_CHARS flag affects the return value when invalid sequences are input.```

Given you are providing a null pointer in the first call, no bytes are written to the buffer.  I am not sure if there is a guarantee of the number being accurate in this case, as the documentation says nothing about how many bytes would have been written were the pointer valid.  There is also the matter of the cost of doing the conversion twice.

I understand the intention was to avoid unnecessary ram allocation, but I am going to reiterate that it seems more prudent to simply allocate a buffer that is a factor of 4 larger than the input string to guarantee it has sufficient space.  It will be freed as soon as the call completes, anyway.

**Comment by ThornyFFXI** [comment]
Never mind, I see, if the last parameter is set to 0 it will return size.  I am still not convinced of the efficiency of this over simply allocating a larger buffer though, I'll try to profile it today.  Presumably the entire conversion needs to be performed to get the exact size.

**Comment by ThornyFFXI** [comment]
Okay, after profiling with the following code:
```
    local itemNameList = T{};
    for i = 1,65535 do
        local item = AshitaCore:GetResourceManager():GetItemById(i);
        if item then
            itemNameList:append(item.Name[1]);
        end
    end


    local time = os.clock();
    for i = 1,100 do
        for _,entry in ipairs(itemNameList) do
            local newName = encoding:ShiftJIS_To_UTF8(entry);
            local ogName = encoding:UTF8_To_ShiftJIS(newName);
        end
    end
    print(string.format('Test one elapsed time: %.6f', os.clock() - time));
    time = os.clock();
    for i = 1,100 do
        for _,entry in ipairs(itemNameList) do
            local newName = encoding:ShiftJIS_To_UTF8_Two(entry);
            local ogName = encoding:UTF8_To_ShiftJIS_Two(newName);
        end
    end
    print(string.format('Test two elapsed time: %.6f', os.clock() - time));

    for _,entry in ipairs(itemNameList) do
        local newName = encoding:ShiftJIS_To_UTF8(entry);
        local newName2 = encoding:ShiftJIS_To_UTF8_Two(entry);
        if (newName ~= newName2) then
            print('SJ->UTF8 Mismatch');
        end

        local ogName = encoding:UTF8_To_ShiftJIS(newName);
        local ogName2 = encoding:UTF8_To_ShiftJIS_Two(newName2);
        if (ogName ~= ogName2) then
            print('UTF8->SJ mismatch');
        end
        if (ogName ~= entry) then
            print('Round trip mismatch');
        end
    end
```
Performance is faster, but only by around 10%, when allocating a suitably oversized buffer (4 * source_length).  Both survive the entire item table and round trip with no access violations or mismatches.  With that in mind, it seems the current revision is stable and the performance difference is not substantial enough to merit alteration.   I'm going to run further tests on the other resource classes in ashita, just to be sure of stability given the past issues.  If it all passes, will merge as is.

**Comment by ThornyFFXI** [comment]
Alright, it seems the following resources fail a round trip(due to ffxi's custom escape codes, not anything in your edit):
Item descriptions
action.messages (string)
a few key items/descriptions(omen beads are the most notable, presumably because of the strange apostrophe being used)

this is probably worth noting, an eventual solution should preserve those escape codes.  But, for the time being, I am merging this.  All other resources provided by ashita pass a round trip in both english and japanese.  No resource provided by ashita triggers any sort of error.

**Comment by onimitch** [comment]
> Alright, it seems the following resources fail a round trip(due to ffxi's custom escape codes, not anything in your edit): Item descriptions action.messages (string) a few key items/descriptions(omen beads are the most notable, presumably because of the strange apostrophe being used)
> 
> this is probably worth noting, an eventual solution should preserve those escape codes. But, for the time being, I am merging this. All other resources provided by ashita pass a round trip in both english and japanese. No resource provided by ashita triggers any sort of error.

Thanks for checking this so thoroughly. FWIW I don't think your suggestion of allocating a 4times buffer instead of requesting the size in advance is a bad idea. The trade-off of CPU vs RAM is always a balancing act. It's interesting it was only around 10% faster though, but then presumably there is some optimisation going on behind the scenes when it's simply calculating the buffer size and not actually doing the conversion.

The issue with some of the item descriptions not matching a conversion both ways is interesting.
In the balloon addon which I've ported to Ashita, they actually pre-process a few characters in advance of utf8 conversion:

string.char(0x81, 0xF4), '[BL_note]' -- musical note
string.char(0x81, 0x99), '[BL_bstar]' -- empty star
string.char(0x81, 0x9A), '[BL_wstar]' -- full star
string.char(0x81, 0x60), '[BL_wave]' -- wide tilde
string.char(0x87, 0xB2), '[BL_cldquote]' -- centered left double quote
string.char(0x87, 0xB3), '[BL_crdquote]' -- centered right double quote
string.char(0x88, 0x69), '[BL_e_acute]' -- acute accented e

These get converted post utf8 conversion as:

'%[BL_note]', '♪'
'%[BL_bstar]', '☆'
'%[BL_wstar]', '★'
'%[BL_wave]', '~'
'%[BL_cldquote]', '“'
'%[BL_crdquote]', '”'
'%[BL_e_acute]', 'é'

So they too must have found some characters failed the roundtrip.

**Pull request merged**
